version: "3.3"
networks: 
   mensageria:
services:
  rabbitmq:
    networks: 
      - mensageria
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 8081:15672
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest'     
  leitor-arquivos:
    networks: 
      - mensageria
    build:
      context: ./leitor-arquivos
    volumes:
      - ./files:/files
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest' 
        RABBITMQ_DEFAULT_HOST: 'rabbitmq' 
        RABBITMQ_DEFAULT_PORT: '5672' 
        RABBITMQ_DEFAULT_EXCHANGE: 'ARQUIVOS' 
        