version: "3.3"
services:
  rabbitmq:
    network_mode: "host"
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest'     
  leitor-arquivos:
    network_mode: "host"
    build:
      context: ./leitor-arquivos
    volumes:
      - ./files:/files
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest' 
        RABBITMQ_DEFAULT_HOST: 'localhost' 
        RABBITMQ_DEFAULT_PORT: '5672' 
        RABBITMQ_DEFAULT_EXCHANGE: 'ARQUIVOS' 
        